---
- name: Check Domain Password Policy
  hosts: your_windows_server
  gather_facts: true
  tasks:
    - name: Get domain password policy settings
      win_shell: |
        $policy = Get-ADDefaultDomainPasswordPolicy
        Write-Output $policy
      register: policy_output

    - name: Display domain password policy settings
      debug:
        var: policy_output.stdout_lines

    - name: Check if PasswordHistorySize is 24 or greater
      set_fact:
        pwpolicyfailed: "{{ policy_output.stdout_lines[0] | regex_search('PasswordHistoryCount\\s*:\\s*(\\d+)') | int < 24 }}"

- name: Change PasswordHistorySize to 24
  hosts: your_windows_server
  gather_facts: true
  tasks:
    - name: Set PasswordHistorySize to 24
      win_shell: |
        Set-ADDefaultDomainPasswordPolicy -PasswordHistoryCount 24
      when: pwpolicyfailed | default(false)
