---

- name: Add host to Windows Active Directory
  hosts: winclient
  gather_facts: false
  vars: 
    admin_username: "{{ adadmuser }}"
    admin_password: "{{ adadmpass }}"
    domain_name: "mp45local.tp"
    hostname: "w10host"
  tasks:

  - name: Join Domain
    microsoft.ad.membership:
      dns_domain_name: "{{ domain_name }}"
      hostname: "{{ hostname }}"
      domain_admin_user: "{{ admin_username }}"
      domain_admin_password: "{{ admin_password }}"
      state: domain
      reboot: true