---

- name: Configure Router for Topology
  hosts: CSR1000V # make sure you have your router in this group
  gather_facts: yes # idk if we need this so i set this to true lol :D
  become: yes
  become_method: enable

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: user
    ansible_password: Password123!
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: Password123!

  tasks:

#Note: This is just a test file: This is here for fallback purposes



